apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: lcasm
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/lcasm-challenge:2655ea16a145534353205d4d0c0787ef88846838e596a46e2fb2a7b2eab4fc13
