apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: solitude
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/solitude-challenge:c43104aa6461be2c6c5ed91061504b52a6640538f2d69ab04de43d8b0823e31a
