apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: ropity
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/ropity-challenge:314de23f377093886b222061eb9363a49ed1f63f99be5022d1107dc04685f8af
