apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: readme2
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "TCP"
        port: 80
        targetPort: 4000
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/readme2-challenge:5df6ea6ceadf2f68996dc4ccbcdca9bc7fa848df78f3fd768c9e233be110e45c
