apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: heapnotes
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: TCP
        targetPort: 443
        domains:
          - "heapnotes.chal.imaginaryctf.org"
  healthcheck:
    enabled: true
    image: eu.gcr.io/imaginaryctf-2023/heapnotes-healthcheck:51197f470ab63741104c2c99588c1e4850df8b22102e96bdb282f1caca30d300
  image: eu.gcr.io/imaginaryctf-2023/heapnotes-challenge:3aa30ebce6f24ea048b505313137e916fd1ff971b3095d897ce2ea1491680b41
