apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: imgstore
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
  healthcheck:
    enabled: false
  image: eu.gcr.io/imaginaryctf-2023/imgstore-challenge:9936ae5a822904fbcb51558fd1bb96acb848dc329c4b464a2175afba2d0d7445
